pipeline{
  agent any
  stages{

    stage('Building Package'){
      steps{
        sh 'maven -f java-tomcat-sample/pom.xml clean package'
      }

      post {
        success{
          echo "Artifacts has been created...Archiving it"
          archiveArtifacts artifacts: '**/*.war'
        }
      }
    }
    
  }
}
